# This workflow will run rsdstats on the RSD data once an hour and push the results to the repo
#
# TODO:
# ttf-mscorefonts-installer fontconfig & sudo fc-cache -f -v

name: rsdstats

on:  
  schedule:   
    - cron: "0 3 * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  rsdstats:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Update ubuntu
        run: sudo apt-get update -y

      - name: Install gnuplot
        run: sudo apt-get install -y gnuplot-nox gsfonts

      - name: Run stats
        run: /bin/bash plot-stats.sh

      - name: Commit result
        run: | 
           git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
           git config --local user.name "github-actions[bot]"
           git add *.data *.png
           git commit -m "Add generated result" -a

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
